#ifndef RACE_COCKPIT_CONFIG_H
#define RACE_COCKPIT_CONFIG_H

#define COCKPIT_SERIAL_BAUD       115200U
#define COCKPIT_PERIOD_MS         20U
#define JOYSTICK_ADC_DEPTH        1U
#define JOYSTICK_DEFAULT_CENTER   2048
#define JOYSTICK_STEERING_CHANNEL 1U

#endif
